# Copyright 2026 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName = "vulnerabilities-frontend"
play.http.router = prod.Routes
play.http.errorHandler = "handlers.ErrorHandler"

play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"
play.modules.enabled += "uk.gov.hmrc.internalauth.client.modules.InternalAuthModule"
play.modules.enabled += "config.Module"

play.filters.enabled += play.filters.csp.CSPFilter
play.i18n.langs = ["en"]

microservice.services.internal-auth {
  protocol = http
  host = localhost
  port = 8470
}

microservice.services.catalogue-config {
  protocol = http
  host = localhost
  port = 9018
}

catalogue-wrapper {
  assets-prefix = "/vulnerabilities-frontend/catalogue-wrapper/assets"
  quick-search-path = "/vulnerabilities-frontend/catalogue-wrapper/quicksearch"
}

catalogue-frontend.base-url = "http://localhost:9017"

microservice.services.vulnerabilities {
  protocol = http
  host = localhost
  port = 8857
}


vulnerabilities.use-stub = true


microservice.services.releases-api {
  protocol = http
  host = localhost
  port = 8008
}


releases-api.use-stub = ${vulnerabilities.use-stub}

releases-api.cache-ttl = 60 seconds


microservice.services.teams-and-repositories {
  protocol = http
  host = localhost
  port = 9015
}
teams-and-repositories.cache-ttl = 1 hour
